language: java
# use Java 11
jdk:
- openjdk8

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

script: ./mvn clean install

notifications:
  email: carlos.junior@aluno.uepb.edu.br
# cache the build tool's caches
#cache:
 # directories:
  #- $HOME/.m2
  #- $HOME/.gradle
